version: '1.0.{build}'
image:
- Ubuntu
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:

build_script:
- docker run -v $PWD:/build --rm mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet publish ./build/DCCS.AspNetCore.FileWatcherService -o /build/output
#- dotnet publish DCCS.AspNetCore.FileWatcherService -o /output
after_build:

test_script:

artifacts:
- path: output\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
