version: '1.0.{build}'
image:
- Ubuntu
configuration:
- Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:

build_script:
- docker run -v $APPVEYOR_BUILD_FOLDER:/build --rm mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build /build/DCCS.AspNetCore.FileWatcherService -o /build/output
#- dotnet build DCCS.AspNetCore.FileWatcherService -o output
after_build:
- ps:  if ($Env:APPVEYOR_REPO_BRANCH -eq "master") { dotnet nuget push /output/*.nupkg -k oy2mdhhwhywyi4y3ajgqacbhqmfuc6ee3ltx4igqkopjnq -s https://api.nuget.org/v3/index.json }
test_script:

artifacts:
- path: /output/**/*.*
cache:
- /var/lib/docker
#- '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
